[tool.poetry]
name = "vamp"
version = "0.1.0"
description = ""
authors = ["dop3file <merlinincorp@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

